### ISSUE TITLE
Make Milestones according to Plan

### ISSUE THREAD

**Issue by rwaming** [rwaming/react_calculator#6]
# Process for Improvement

## Essential
- [ ] Check file the reviewer made

#### 1. Rename
- [ ] Rename file extentions to JSX, if it uses JSX
- [ ] Check all names of variables, functions, files
#### 3. Move functions
- [ ] Function has only a function.
- [ ] Module can be read easily, and has functions only related to it.
#### 4. Make nav's modal
- [ ] Put a modal on nav's backward, which is transparent or grey..
- [ ] or Use event listener and class name like -modal
#### 5. Data have to be send from parent to child
- [ ] Use React.useContext

### Make code **"React"**
> React is made to use just variable data, not UI like elements, css.
- [ ] .map
- [ ] if
- [ ] component

#### Animation (disappear)
- [ ] @media query
- [ ] React Transition Group
- [ ] Event "animationed"

#### Math
- [ ] Use Math object to root, percent, etc..
